#############################################################################################################################################
#    This script is generated by the Azure AD Connect Configuration Documenter tool.
#    The latest version of the tool can be downloaded from https://aka.ms/AADConnectConfigDocumenter.
#
#    NO WARRANTY OF ANY KIND IS PROVIDED. THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SCRIPT REMAINS WITH THE USER.
#
#    When the script is executed, the sync rule configuration of the server is made same as what was provided as the "Pilot" configuration.
#    The "Pilot" configuration was the first argument passed when running the AAD Connect Config Documenter executable.
#############################################################################################################################################

function Get-CurrentLine {
    $Myinvocation.ScriptlineNumber
}

$Error.Clear()
Clear-Host

