//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureADConnectConfigDocumenter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumenterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumenterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureADConnectConfigDocumenter.DocumenterResources", typeof(DocumenterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pilot / target configuration directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string PilotConfigurationDirectoryNotFound {
            get {
                return ResourceManager.GetString("PilotConfigurationDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#
        ///    This script is generated by the Azure AD Connect Configuration Documenter tool.
        ///    The latest version of the tool can be downloaded from https://aka.ms/AADConnectConfigDocumenter.
        ///
        ///    NO WARRANTY OF ANY KIND IS PROVIDED. THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SCRIPT REMAINS WITH THE USER.        ///#&gt;
        ///
        ///######################################################################################################################################
        ///
        ///function Get-CurrentLine {
        ///    $Myinvoca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerShellScriptHeader {
            get {
                return ResourceManager.GetString("PowerShellScriptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ######################################################################################################################################
        ///#### &apos;{0}&apos; - &apos;{1}&apos;
        ///######################################################################################################################################
        ///
        ///Write-Host (&quot;Line# &quot; + (Get-CurrentLine)).
        /// </summary>
        internal static string PowerShellScriptSectionHeader {
            get {
                return ResourceManager.GetString("PowerShellScriptSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The production / baseline / reference configuration directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string ProductionConfigurationDirectoryNotFound {
            get {
                return ResourceManager.GetString("ProductionConfigurationDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    margin-top: 10px;
        ///    margin-left: 10px;
        ///    margin-right: 10px;
        ///    margin-bottom: 10px;
        ///    font-family: Calibri,Tahoma;
        ///}
        ///
        ///table {
        ///    font-family: Calibri,Tahoma;
        ///    font-size: 10pt;
        ///    padding: 0;
        ///    border-collapse: collapse;
        ///    width: 100%;
        ///    white-space: pre-wrap;
        ///}
        ///
        ///    table.outer-table {
        ///        width: 600pt;
        ///    }
        ///
        ///th {
        ///    text-align: left;
        ///    padding-left: 10px;
        ///    padding-right: 10px;
        ///}
        ///
        ///    th.column-th {
        ///        font-weight: bold;
        ///        font [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
    }
}
